### ISSUE TITLE
test_sockets.py::TestAIOSockets test timing out with 3.8.1

### ISSUE THREAD

**Issue by doko42** [MagicStack/uvloop#318]
[forwarding from https://bugs.debian.org/950165]

test_sockets.py::TestAIOSockets tests are timing out with 3.8.1, see this change in all active Python branches: https://bugs.python.org/issue37228

**Comment by 1st1** [comment]
Thanks for creating this issue!

**Comment by fantix** [comment]
Port of [bpo-37228](https://bugs.python.org/issue37228) is applied in https://github.com/MagicStack/uvloop/pull/343, but this Debian bug is actually caused by [bpo-30064](https://bugs.python.org/issue30064), I think at the moment we could safely skip the hanging test `tests.test_sockets.TestAIOSockets.test_sock_cancel_add_reader_race` before there's a proper fix.

**Comment by fantix** [comment]
fixed in #346 and python/cpython#20369

**Comment by jonringer** [comment]
This is still an issue on python 3.8.3.

Trying to update nixpkgs package https://github.com/jonringer/nixpkgs/commit/c7a69037ba512da3a244d5270bc189fbd77b2b4a off of latest master, and test suite still hangs. Unfortunately I'm not sure what tests is hanging

**Comment by fantix** [comment]
right - sorry I think we should skip the whole Python 3.8 as the fix was only backported to 3.9. I'll create a PR for that.
