### ISSUE TITLE
uvloop crashed and core dumped

### ISSUE THREAD

**Issue by cwt** [MagicStack/uvloop#41]
* **uvloop version**: 0.4.33
* **python version**: 3.5.1
* **platform**: VMware Photon Linux 1.0

I just rebuild my [wormhole proxy](https://bitbucket.org/bashell-com/wormhole) docker image today ([Dockerfile](https://goo.gl/pjYO1Q)). After I use it for a few minutes, it crashed and show error messages like these (randomly on each time it crashed).

> python3.5: src/unix/core.c:236: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.

or

> python3.5: src/unix/core.c:264: uv__finish_close: Assertion `0' failed.

or

> python3.5: src/unix/stream.c:444: uv__stream_destroy: Assertion `(((const QUEUE *) (&(stream->loop)->active_reqs) == (const QUEUE *) (*(QUEUE **) &((*(&(stream->loop)->active_reqs))[0]))) == 0)' failed.

I also tried to build it on Alpine Linux image ([Dockerfile](https://goo.gl/GM15Tk)) the result is also the same.

BTW, I have no problem with the previous image that was built around 2 weeks ago, the uvloop version on that image was 0.4.30.

**Comment by 1st1** [comment]
Could you please tell how to run your proxy without docker? I.e. should I just clone the repo and run some script? How to enable uvloop in it?

**Comment by 1st1** [comment]
I've just committed a small change - 2b060e170fc45ec0965bab926513725f9714c73b - please check if it fixes the problem.

**Comment by cwt** [comment]
to run it without docker:

    $ pyvenv-3.5 wormhole
    $ source wormhole/bin/activate
    (wormhole) $ pip install Cython
    (wormhole) $ pip install uvloop
    (wormhole) $ pip install wormhole-proxy
    (wormhole) $ wormhole

I'm cloning and building uvloop from git now. Will post the results again after finish.

**Comment by cwt** [comment]
unfortunately, it still crashed with the same error messages.

**Comment by 1st1** [comment]
> to run it without docker:

Thanks! And what should I do to crash it?

**Comment by 1st1** [comment]
OK, I got it. Once I set up Firefox to use it, it crashed almost instantly.

**Comment by 1st1** [comment]
Should be fixed by 7b0b195d100ccd63d6b5cd56e36b099ad6ace8b4. Will issue a new release soon.

**Comment by 1st1** [comment]
Please try uvloop `v0.4.34`.

**Comment by cwt** [comment]
Yeah! my proxy work pretty well with v0.4.34. Thank you.

**Comment by 1st1** [comment]
Thanks! See also https://github.com/MagicStack/uvloop/issues/37#issuecomment-232165394.

**Comment by Mark90** [comment]
Sorry to bump an ancient thread. I just noticed an almost identical error in our application (running in k8s but that's probably not relevant)

The exact error has a slightly different line version than in OP (but it's 7 years later so 🤷 )

> python: src/unix/core.c:259: uv__finish_close: Assertion `!(handle->flags & UV_HANDLE_CLOSED)' failed.

I just see 1 occurrence of it from 2 weeks back, all other k8s pods have been running fine. So there doesn't seem to be a permanent problem, but I'll just leave some breadcrumbs here.

Software versions:
```
Uvloop: 0.17.0
Docker base image: python:3.11-slim
Python version: 3.11.3
```

Not sure if any of the other python package versions matter, but just in case:
```
anyio 3.7.0
hypercorn 0.14.3
starlette 0.27.0
``` 

Output of several commands ran from the k8s pod, i.e. about the host OS:
```
www-data@production-ims-fbcfff76-jt84d:/usr/src/app$ uname -a
Linux production-ims-fbcfff76-jt84d 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 x86_64 GNU/Linux
www-data@production-ims-fbcfff76-jt84d:/usr/src/app$
www-data@production-ims-fbcfff76-jt84d:/usr/src/app$ source /etc/os-release && echo $PRETTY_NAME
Debian GNU/Linux 11 (bullseye)
```
