### ISSUE TITLE
uvloop breaks aiohttp's capability of serving static files

### ISSUE THREAD

**Issue by diogobaeder** [MagicStack/uvloop#50]
* **uvloop version**: 0.5.3
* **python version**: 3.5.2
* **platform**: Arch Linux / 4.7.1-1-ARCH / x86_64

`uvloop` breaks aiohttp's capability of serving static files. It makes the server send the response headers after the body.

To run this, have aiohttp and uvloop installed, then run the gist ( https://gist.github.com/diogobaeder/0558c43d785cd82a1ecff553bc583867 ):
`$ python uvhttp.py`

Then make a request to the app, making sure to get verbose output:
`$ curl -v localhost:8765/jquery.js`

These are the results I'm getting when serving jQuery:

1. Without uvloop (correct response): http://pastebin.com/e6ep3g22
2. With uvloop (bad response): http://pastebin.com/Kg37DXB8

Notice how with uvloop the response headers are sent after the body.

I'm not acquainted with the internals of `aiohttp` or `uvloop`, but it seems that the former relies on some parser from `asyncio` and `uvloop` seems to replace it by another one that behaves differently.

Any ideas of why this happens? At the moment this is preventing me to use `uvloop`, unfortunately...

Thanks!

**Comment by 1st1** [comment]
What version of aiohttp are you using?  AFAIK there was an issue with how aiohttp implemented sendfile, which was fixed not long ago.

cc @asvetlov

**Comment by diogobaeder** [comment]
Hi @1st1 ,

Unfortunately I'm already using the latest version, which is `0.22.5`. Mind trying it as well, and see if it works fine for you?

Thanks for the quick reply :-)

**Comment by asvetlov** [comment]
There is KeepSafe/aiohttp#1093 issue.
It's still not fixed but very reproducible.
I think aiohttp sends headers into transport's buffer but sendfile sends a content directly through the wire, that's why headers are sent too late.

**Comment by diogobaeder** [comment]
Hmmm... makes sense...

Should we close this issue as a duplicate? Want me to refer it in the other one?

**Comment by asvetlov** [comment]
@1st1 please close the issue as  KeepSafe/aiohttp#1093 is resolved.

**Comment by 1st1** [comment]
@asvetlov When will you release aiohttp with this thing fixed?

**Comment by asvetlov** [comment]
@1st1 just after fixing bugs with cookiejar.
In a few days I hope.

**Comment by 1st1** [comment]
Closing the issue since it has been resolved in aiohttp.
